# Pocket Pantry Android Client Build

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- script: npm install -g ionic
  displayName: 'Install Ionic'

- script: npm install -g cordova
  displayName: 'Install Cordova'

- script: npm install src/Client
  displayName: 'npm install'

- script: | 
    cd src/Client
    ionic cordova build android
  displayName: 'Ionic Android Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
