# Pocket Pantry Android Client Build

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: Npm@1
  displayName: 'Install Ionic CLI'
  inputs:
    command: custom
    verbose: false
    customCommand: install -g ionic

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: src/Client
    verbose: false

- script: ionic cordova build android
  displayName: 'Ionic Android Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
