# Pocket Pantry Android Client Build

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: sudo npm install -g ionic
  displayName: 'Install Ionic'

- script: sudo npm install -g cordova
  displayName: 'Install Cordova'

- script: sudo npm install src/Client
  displayName: 'npm install'

- script: cd src/Client && sudo ionic cordova build android
  displayName: 'Ionic Android Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
